### ISSUE TITLE
ohgodwhy.jpg

### ISSUE THREAD

**Issue by nateberkopec** [TechAtNYU/TNYU_IRCbot#2]
if you type in:

```
ohgodwhy.jpg
```

or anything else that matches a regex of a similar one-line image name (derp.png, whatthe.gif), the IRC bot should google image search the filename (in the example, ohgodwhy) and post the first result to the chat

**Comment by wyattisimo** [comment]
`AutoImage` plugin = done-zoar.  feel free to enhance.
