### ISSUE TITLE
AutoImage should not repeat images

### ISSUE THREAD

**Issue by nateberkopec** [TechAtNYU/TNYU_IRCbot#6]
When asked to generate the same image again (tnyubot.jpg twice for example), it should never generate the same image twice.

The right way to do this would probably be to memoize the results of a given query (released periodically, every 5 minutes or so) and then delete the image from the query memo when it is used in chat

**Comment by wyattisimo** [comment]
i enabled duplicate content filter on google's search results, so every image has a 1/n chance.  that should help a little.
